/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package SimulasiUTSPBO;

import java.sql.*;
import java.util.logging.*;
import javax.swing.*;
import javax.swing.table.*;
import java.awt.event.*;
import java.util.ArrayList;
import java.io.*;

public class Buku extends javax.swing.JFrame {
    Connection connect;
    String a,b,c,d;
    
    
    String Driver = "org.postgresql.Driver";
    String Koneksi = "jdbc:postgresql://localhost:5432/PBO_Simulasi_UTS";
    String User = "postgres";
    String Password = "muklishotin";
    
    private final ArrayList<String[]> list = new ArrayList<>();
    private final String[] kolom = {"isbn", "judul_buku", "tahun_terbit", "penerbit"};
    
    
    
    public Buku() {
        initComponents();
        this.getAllData();
        this.refreshModel();
    }
    
     public final void getAllData() {
        try {
            list.clear();
            String sql = "SELECT * FROM Buku";
            connect = DriverManager.getConnection(Koneksi, User, Password);
            PreparedStatement ps = connect.prepareStatement(sql);
            ps.executeQuery();
            final ResultSet data = ps.getResultSet();
            while (data.next()) {
                final String[] row = new String[]{
                    data.getString("isbn"),
                    data.getString("judul_buku"),
                    data.getString("tahun_terbit"),
                    data.getString("penerbit")
                };

                list.add(row);
            }
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }

    public final void refreshModel() {
        DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(kolom);
        for (String[] data : list) {
            model.addRow(data);
        }
        tbbuku.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        tfisbn = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        tfjudulbuku = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tftahunterbit = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfpenerbit = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbbuku = new javax.swing.JTable();
        btninput = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        btnbersihkan = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tfisbn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfisbnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Judul Buku");

        tfjudulbuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfjudulbukuActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("ISBN");

        tftahunterbit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tftahunterbitActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Penerbit");

        tfpenerbit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfpenerbitActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Tahun Terbit");

        tbbuku.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ISBN", "Judul Buku", "Tahun Terbit", "Penerbit"
            }
        ));
        jScrollPane3.setViewportView(tbbuku);

        btninput.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btninput.setText("INPUT DATA");
        btninput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btninputActionPerformed(evt);
            }
        });

        btnupdate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnupdate.setText("UPDATE");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });

        btndelete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btndelete.setText("HAPUS DATA");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });

        btnbersihkan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnbersihkan.setText("BERSIHKAN");
        btnbersihkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbersihkanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tftahunterbit, javax.swing.GroupLayout.DEFAULT_SIZE, 554, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfisbn)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfjudulbuku, javax.swing.GroupLayout.DEFAULT_SIZE, 554, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfpenerbit, javax.swing.GroupLayout.DEFAULT_SIZE, 554, Short.MAX_VALUE))
                .addContainerGap(76, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btninput, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btndelete)
                .addGap(18, 18, 18)
                .addComponent(btnbersihkan)
                .addGap(95, 95, 95))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfisbn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfjudulbuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tftahunterbit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfpenerbit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btninput)
                    .addComponent(btnupdate)
                    .addComponent(btndelete)
                    .addComponent(btnbersihkan, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfisbnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfisbnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfisbnActionPerformed

    private void tfjudulbukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfjudulbukuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfjudulbukuActionPerformed

    private void tftahunterbitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tftahunterbitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tftahunterbitActionPerformed

    private void tfpenerbitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfpenerbitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfpenerbitActionPerformed

    private void btninputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btninputActionPerformed
        a = tfisbn.getText();
        b = tfjudulbuku.getText();
        c = tftahunterbit.getText();
        d = tfpenerbit.getText();

        if (a.trim().isEmpty() || b.trim().isEmpty() || c.trim().isEmpty() || d.trim().isEmpty()) {
            JOptionPane.showMessageDialog(btninput, "TERDAPAT DATA YANG KOSONG");
        } else {
            try {
                String sql = "insert into Buku (isbn,judul_buku,tahun_terbit,penerbit) values (?,?,?,?)";
                PreparedStatement ps = connect.prepareStatement(sql);
                ps.setString(1, a);
                ps.setString(2, b);
                ps.setString(3, c);
                ps.setString(4, d);
                ps.executeUpdate();

                this.getAllData();
                this.refreshModel();
                tfisbn.setText("");
                tfjudulbuku.setText("");
                tftahunterbit.setText("");
                tfpenerbit.setText("");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(btninput, "INPUT DATA GAGAL");
            }
        }
        
    }//GEN-LAST:event_btninputActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        a = tfisbn.getText();
        b = tfjudulbuku.getText();
        c = tftahunterbit.getText();
        d = tfpenerbit.getText();

        if (a.trim().isEmpty() || b.trim().isEmpty() || c.trim().isEmpty() || d.trim().isEmpty()) {
            JOptionPane.showMessageDialog(btnupdate, "TERDAPAT FIELD YANG KOSONG");
        } else {
            try {
                String sql = "update Buku set judul_buku =?, tahun_terbit = ?, penerbit= ? where isbn = ?";
                PreparedStatement ps = connect.prepareStatement(sql);
                ps.setString(1, b);
                ps.setString(2, c);
                ps.setString(3, d);
                ps.setString(4, a);
                int baris = ps.executeUpdate();
                if (baris > 0) {
                    this.getAllData();
                    this.refreshModel();
                }

                tfisbn.setText("");
                tfjudulbuku.setText("");
                tftahunterbit.setText("");
                tfpenerbit.setText("");

            } catch (Exception e) {
                System.out.println(e.getMessage());
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        }

    }//GEN-LAST:event_btnupdateActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        a = tfisbn.getText();

        if (a.trim().isEmpty()) {
            JOptionPane.showMessageDialog(btndelete, "TERDAPAT DATA YANG KOSONG");
        } else {
            try {
                String sql = String.format("delete from Buku where isbn = '%s'", a);
                Statement s = connect.createStatement();
                s.executeUpdate(sql);
                JOptionPane.showMessageDialog(this, "Data Telah Terhapus");
                this.getAllData();
                this.refreshModel();
              
                tfisbn.setText("");
                tfjudulbuku.setText("");
                tftahunterbit.setText("");
                tfpenerbit.setText("");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(btndelete, "INPUT DATA GAGAL");
            }
        }
    }//GEN-LAST:event_btndeleteActionPerformed

    private void btnbersihkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbersihkanActionPerformed
          try {
            tfisbn.setText("");
            tfjudulbuku.setText("");
            tftahunterbit.setText("");
            tfpenerbit.setText("");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnbersihkanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Buku().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbersihkan;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btninput;
    private javax.swing.JButton btnupdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tbbuku;
    private javax.swing.JTextField tfisbn;
    private javax.swing.JTextField tfjudulbuku;
    private javax.swing.JTextField tfpenerbit;
    private javax.swing.JTextField tftahunterbit;
    // End of variables declaration//GEN-END:variables
}
